### ISSUE TITLE
How to install that plugin?

### ISSUE THREAD

**Issue by Dmgerr** [jwileyfl/streamdeck-freestyler#14]

**Comment by jwileyfl** [comment]
I haven't created an installer for it yet, so after you build it, you have to manually copy it to the streamdeck plugin folder (i.e. on a windows pc:  %appdata%\Elgato\StreamDeck\Plugins\)

**Comment by jwileyfl** [comment]
I haven't really done anything with it in a while, but I will look at making some small updates and adding an installer/msi to the next release.

**Comment by jwileyfl** [comment]
I'm just getting around to this.  Now that I'm looking at it, I'm remembering what I did.  In the FreestylerRemote folder there's a Windows shell script 'build.cmd'.  Execute this script and it will create a 'DistributionPackage' folder.  The plugin will be located within that folder.  Navigate there and execute it.  That will install the plugin.  I'll still create an msi installer for it as well.

**Comment by jwileyfl** [comment]
I've attached the binary plugin to the release tag

**Comment by jwileyfl** [comment]
Added a simple wix installer project to the solution and attached the .msi to the release tag
